### ISSUE TITLE
version-3.3.0 access denied

### ISSUE THREAD

**Issue by Motophan** [linuxserver/docker-sabnzbd#105]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I noticed that fresh containers on version-3.3.0 will not let you access the web UI. I attempted to join the discord server to informally report the bug but it turns out that my two suggestions from approximately 6 months ago caused a permanent ban. 

their respective discord issues are 
https://github.com/linuxserver/docker-quassel-core/issues/45

https://github.com/linuxserver/docker-nextcloud/issues/200

the core of the problem is that I feel genuine suggestions should have some level of free conversation. meaning I could suggest a documentation fix and explain why as long as I did it appropriately. I tried this and then was permanently banned; I suggested that it might be helpful to recommend users use a DB backend for quassel as it would become unusable after 6 months and that there was an issue with how linucservers nextcloud implementation causes a http 400 error in some cases. both of these were genuine suggestions, meaning that I thought my individual experience brought value to the conversation. the moderator did not think this and permanently banned me from any access to the discord for over 6 months. I think that's slightly severe for something that did not involve any swear words or (from my point of view) disrespect to a person. suggesting that something may be improved is not disrespecting the person, just that there may be possible value in other people's opinions. l
------------------------------

## Expected Behavior

not say "access denied" on a new container
## Current Behavior

says "access denied"
## Steps to Reproduce

1. install container
2. go to webui
3. 
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by Roxedus** [comment]
This is due to a upstream change, Sab documented this change poorly, but they did mention it. 

> The External internet access will automatically detect local network
and no longer requires local network ranges to be defined. Custom ranges
can still be defined through local_ranges in Special settings.

\- [SABnzbd 3.3.0](https://github.com/sabnzbd/sabnzbd/releases/tag/3.3.0)

*A* fix is to the container name to `host_whitelist()`, or add your range to `local_rangers()`, both options should be found under special settings. 



Now to the off-topic part. 

Criticizing our work, or telling us it could be better( with a reasonable resolution) is **not** the reason you got banned. The reasons include:

* Bringing up claims without proof when challenged (ref NC(or instance is still the same, no problems, it has outlived the 2-month lifetime you claim it has, by a lot),  when challenged you were rude, and saying team-members are wrong.
* Bully people to give out info they clearly don't want to share (ISP names comes to mind)

I know IPV6 is important to you, you do not however need to force it down the throats on people that do not want to deal with this for the time being, not everyone understands networking.

**Comment by Motophan** [comment]
![image0-3](https://user-images.githubusercontent.com/42502676/120467510-bb2ab080-c34c-11eb-94c0-8fcd36dfc9b2.png)
this is the message that caused me to get banned. I don't see anything about IPv6 or something if that nature or ISP names. that doesn't sound like something I would say but I was in the discord for a long time so I may have said something that someone may have taken the wrong way at some point before my ban. months maybe? I don't know I don't remember. 

you're right, I could have been better.


Can I be unbanned, as this is kind of a dead/buried issue from way back isn't very severe. we're not talking about me insulting people we're talking about me being slightly less respectful than desired.

thanks.

**Comment by Roxedus** [comment]
That message is just the drop that tipped the glass, after refusing to show any proof, or will to get support for what *might* have been confusion or user error (I don't know, never saw any logs).

**Comment by Motophan** [comment]
what you're saying I was a horrible user but hear me on on this please.

1) it's been 6 months

2) if I did have a bad conversation with a few people that won't happen again you have my word on this.

3) I didn't come into the discord with malice in mind where I'm trying to cause annoyance. it was just a personality issue that's been solved. really when you see troll accounts you see them tagging people over and over or posting inappropriate images. none of that has ever happened with my account. 




can I get an unban please?

**Comment by MrGreenTea** [comment]
Hi guys and thanks for the great work you do with dockerizing all these nice tools!
I currently have to stay on version 3.2.1 because with 3.3.0 I get 403 errors from sonarr and others.
It works from the browser though 🤷 

In sonarr I get an error like
```
Test was aborted due to an error: Unable to connect to SABnzbd, HTTP request failed: [403:Forbidden] [GET] at [http://sabnzbd:8080/api?mode=get_config&apikey=XXXXXXXX&output=json]
```

Changing `host_whitelist()` to `sabnzbd` helped with this. Is there a way to make this automatic, so it survives new deployments?

**Comment by aptalca** [comment]
no, host whitelist has to be edited in the gui. You had to do the same thing for the whole url if reverse proxying, now you have to add the hostname as well (and any other name you use to connect to sab). It's a security feature of sab
