### ISSUE TITLE
Watched Folder

### ISSUE THREAD

**Issue by Jozzy1983** [linuxserver/docker-sabnzbd#41]
I am now in the process of moving all my NAS applications over to Docker containers.
Only moments ago I started to use the SabNzb container you provide and I am very happy with it.

The only downside at this moment is that I cant seem to mount my Watched Folder.

Would it be possible to add Watched Folder as /watch parameter?

I believe it would make this container more functional 👍 :)

Ps; My watched folder is located on a USB stick. The NAS I use is a Synology. I use a USB stick to save my hard disks.

**Comment by tobbenb** [comment]
You can add a folder mount yourself without us adding anything. Then point to that folder in sabnzbd. 
But if you unplug and insert your USB, that will not work as docker needs access to the device when the service is started.

**Comment by Jozzy1983** [comment]
Well I tried that but then I get the error "Container does not exist".
And when I remove the added mount the container functions again.
Also when I add the /watch mount when creating the container, the error occurs.
Thats why I draw the conclusion the /watch should be known as parameter.

**Comment by tobbenb** [comment]
As i said before, this is most likely caused by you using a USB stick that was not inserted when the docker service started. If you can stop and start the docker service, try that with the USB stick inserted. Then add the /watch mount.
This is not an error with the container, but something on your end.
Docker run command would be good to post also. We don't have a synology so we donæt know how it works.
