### ISSUE TITLE
No scripts folder

### ISSUE THREAD

**Issue by ChuckyNorris** [linuxserver/docker-sabnzbd#58]
Hi

I am running this container on a Raspberry Pi 3B running LibreELEC.  I have SickChill running in a separate container.
When doing set-up in the web UI, I wanted to use the SABtoSickbeard script that I used with my previous set-up (Isellens Audo) but the scripts drop-down on the categories page is greyed out.  I went to the folders menu to check the scripts folder and found that there isn't a scripts folder set, nor could I find an appropriate folder to use.
Is there a reason this image has no scripts folder?  Why not include the SABtoSickbeard script by default?  I imagine a lot of people would use it.

Regards
Chuck

**Comment by sparklyballs** [comment]
if you want a scripts folder, make one, either in the /config volume mount or elsewhere if you want it on a separate volume mount from /config

navigate to folders section of settings and set the scripts folder location to match the internal side of the volume mount (if created a new one) or make it relative to the /config folder internally.

![screenshot 2019-03-01 at 10 05 33](https://user-images.githubusercontent.com/4343808/53631094-a27d3e80-3c09-11e9-9059-30817380c6d8.png)

We don't add any scripts, because then are dependency issues and tom dick and harry wanting script x and we end up with bloat.
